# Data source
spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: aplicacao-financeira

# Database
  database:
    driverClassName: org.postgresql.Driver

# Jackson
  jackson:
    serialization:
      fail-on-empty-beans: false

# JPA
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# Server
server:
  port: 8080

# Swagger
springdoc:
  swagger-ui:
    operations-sorter: alpha